### ISSUE TITLE
Error when importing omnipath?

### ISSUE THREAD

**Issue by jadeshi** [saezlab/omnipath#8]
Hi,
I recently installed omnipath via "pip install omnipath" in a conda environment with python 3.6, but when I try to import it, I get the following error:

>>> import omnipath
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jshi/miniconda2/envs/pypath2021/lib/python3.6/site-packages/omnipath/__init__.py", line 2, in <module>
    from omnipath._core.utils import options  # from_first in isort is important here
  File "/Users/jshi/miniconda2/envs/pypath2021/lib/python3.6/site-packages/omnipath/_core/utils/__init__.py", line 1, in <module>
    from omnipath._core.utils._options import options
  File "/Users/jshi/miniconda2/envs/pypath2021/lib/python3.6/site-packages/omnipath/_core/utils/_options.py", line 8, in <module>
    from omnipath.constants import License
  File "/Users/jshi/miniconda2/envs/pypath2021/lib/python3.6/site-packages/omnipath/constants/__init__.py", line 1, in <module>
    from omnipath.constants._constants import License, Organism, InteractionDataset
  File "/Users/jshi/miniconda2/envs/pypath2021/lib/python3.6/site-packages/omnipath/constants/_constants.py", line 75, in <module>
    class License(PrettyEnumMixin):
  File "/Users/jshi/miniconda2/envs/pypath2021/lib/python3.6/site-packages/enum_tools/documentation.py", line 76, in document_enum
    func_source = dedent(inspect.getsource(an_enum))
  File "/Users/jshi/miniconda2/envs/pypath2021/lib/python3.6/inspect.py", line 973, in getsource
    lines, lnum = getsourcelines(object)
  File "/Users/jshi/miniconda2/envs/pypath2021/lib/python3.6/inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "/Users/jshi/miniconda2/envs/pypath2021/lib/python3.6/inspect.py", line 768, in findsource
    file = getsourcefile(object)
  File "/Users/jshi/miniconda2/envs/pypath2021/lib/python3.6/inspect.py", line 684, in getsourcefile
    filename = getfile(object)
  File "/Users/jshi/miniconda2/envs/pypath2021/lib/python3.6/inspect.py", line 654, in getfile
    raise TypeError('{!r} is a built-in class'.format(object))
TypeError: None is a built-in class

This is from an installation on a Mac, but I've also tried installing on Linux with the same behavior. Wondering if this is a known issue and what the reason is? Thanks!

**Comment by deeenes** [comment]
Hi @jadeshi,

This module requires Python 3.7 as it uses more recent features of the standard library.
Python 3.6 is a quite old version, reaching its end of life in 9 months from now. I recommend to use omnipath with the current version 3.9 or at least 3.7. In Python 3.6 I could reproduce the error above, while in Python 3.7 I could import the module with no error.

Best,

Denes
